version: '3.4'

services:
  petportalapi:
    image: ${DOCKER_REGISTRY-}petportalapi
    build:
      context: .
      dockerfile: PetPortalAPI/PetPortalAPI/Dockerfile
    depends_on:
            - postgres

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "petportaldb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345678"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"
    volumes:
      - ./minio-data:/data
        
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      
volumes: 
  postgres-data:
  redis_data: