name: Deploy to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          set -e
          echo "Starting deployment..."
          
          # Переходим в директорию с репозиторием
          cd /path/to/your/repository
          
          # Обновляем код
          git fetch origin
          git reset --hard origin/main
          
          # Копируем необходимые файлы на уровень выше
          cp -f docker-compose.yml ../
          cp -f nginx.conf ../  # если есть nginx конфиг
          # cp -f .env ../       # если используете .env файл
          
          # Переходим в директорию с docker-compose
          cd ..
          
          # Перезапускаем контейнеры
          docker-compose down
          docker-compose build --no-cache
          docker-compose up -d
          
          echo "Deployment completed successfully!"
